[project]
name = "strip-marks"
version = "1.0.0"
description = "Small Python library to strip non-spacing marks (e.g., diacritics) from a string"
authors = [
    { name = "Jake W. Ireland", email = "jakewilliami@icloud.com" },
]
readme = "README.md"
requires-python = ">=3.11, <4.0.0"
license = { text = "MIT" }
dependencies = [
    "ispunct>=1.0.0",
]

[dependency-groups]
dev = [
    "pip-audit>=2.9.0",
    "pre-commit>=4.3.0",
    "pytest==8.3.4",
    "ruff>=0.12.8",
]

[tool.uv.sources]
ispunct = { git = "https://github.com/jakewilliami/ispunct-py", tag = "v1.0.0" }

[tool.pytest.ini_options]
pythonpath = "src"

[tool.ruff]
# https://peps.python.org/pep-0008/#maximum-line-length
line-length = 80

[tool.ruff.lint]
select = [
    "E",    # pycodestyle
    "F",    # Pyflakes
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "SIM",  # flake8-simplify
    "I",    # isort
]
ignore = [
    # "B008",  # docs.astral.sh/ruff/rules/function-call-in-default-argument/
]
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]  # Unused imports
